[STORAGE]
SQLITE_DB = "db/devika.db"
SCREENSHOTS_DIR = "screenshots"
PDFS_DIR = "pdfs"
PROJECTS_DIR = "projects"
LOGS_DIR = "logs"
REPOS_DIR = "repos"

[API_KEYS]
BING = "<YOUR_BING_API_KEY>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"
OPENAI = "<YOUR_OPENAI_API_KEY>"
AZURE_OPENAI = "<YOUR_AZUREAI_API_KEY>"

[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"
AZURE_OPENAI = "<YOUR_AZUREAI_ENDPOINT>"

[DEPLOYMENT_NAME]
AZURE_OPENAI_ENGINE = "<YOUR_AZUREAI_DEPLOYMENT_NAME>"

[API_VERSION]
AZURE_API_VERSION = "<YOUR_AZUREAI_API_VERSION>"